# Generated by Django 6.0 on 2025-12-07 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViolenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=100)),
                ('violence_type', models.CharField(choices=[('physical', 'Physical Violence'), ('sexual', 'Sexual Violence'), ('emotional', 'Emotional Abuse'), ('economic', 'Economic Abuse'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=300)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Violence Report',
                'verbose_name_plural': 'Violence Reports',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
