# Generated by Django 6.0 on 2026-05-08 14:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_violencereport_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Logged In'), ('logout', 'Logged Out'), ('view_report', 'Viewed Report'), ('create_report', 'Created Report'), ('update_status', 'Updated Report Status'), ('edit_report', 'Edited Report'), ('delete_report', 'Deleted Report'), ('download_evidence', 'Downloaded Evidence'), ('export_data', 'Exported Data'), ('filter_reports', 'Filtered Reports'), ('search_reports', 'Searched Reports')], max_length=50)),
                ('description', models.TextField()),
                ('report_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Activity Log',
                'verbose_name_plural': 'Admin Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
