# Generated by Django 6.0 on 2026-05-20 15:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_adminlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='reports.violencereport')),
            ],
            options={
                'verbose_name': 'Report Follow Up',
                'verbose_name_plural': 'Report Follow Ups',
                'ordering': ['-created_at'],
            },
        ),
    ]
